import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './conponents/navbar/Navbar'
import Home from './conponents/home/Home'
import Blog from './conponents/blog/page'
import Features from './conponents/features/Features'
import Review from './conponents/reviews/Review'
import About from './conponents/about/About'
import Contact from './conponents/contacts/Contact'
import Footer from './conponents/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} >
        {/* <div className='shadow-slate-50 max-w-screen-xl bg-gray-400 ma justify-center'> */}
        <div className='cstmindex'> 
         <Navbar />
         </div>
         

          <Home />
          <Blog />
          <Features />
          <Review />
          <About />
          <Contact />
          <Footer />
          {/* {children} */}
        {/* </div> */}
        </body>
    </html>
  )
}
